name: Test

on:
  push:
  pull_request:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm test
      env:
        REGISTRY_REPOSITORY: https://github.com/ISDCF/registries
        PORT: 30000
   
